# Generated by Django 4.0.1 on 2022-01-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vTitle1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
