# Generated by Django 4.0.1 on 2022-01-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0003_product_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dates',
            new_name='dates1',
        ),
    ]
