# Generated by Django 4.0.1 on 2022-01-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0004_rename_dates_product_dates1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dates1',
        ),
    ]
