# Generated by Django 4.0.1 on 2022-01-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0005_remove_product_dates1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pDate',
            field=models.DateField(null=True, verbose_name='Date (mm/dd/yy)'),
        ),
    ]
