# Generated by Django 4.0.1 on 2022-01-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0007_remove_product_id_product_iproductid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iProductId',
            new_name='id',
        ),
    ]
