# Generated by Django 4.0.1 on 2022-01-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0009_rename_id_product_iproductid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date (mm/dd/yy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date (mm/dd/yy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vTitle',
            field=models.CharField(max_length=255, verbose_name='Product Title'),
        ),
    ]
