# Generated by Django 4.0.1 on 2022-01-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhargav', '0011_product_vsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dPriceF',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
